language: objective-c
osx_image: xcode9.4

env:
  global:
    - PROJECT=Stenographer.xcodeproj
    - SCHEME_MACOS="Stenographer macOS"
    - SCHEME_IOS="Stenographer iOS"
    - SCHEME_TVOS="Stenographer tvOS"
    - SCHEME_WATCHOS="Stenographer watchOS"

  matrix:
    - TOOL="XCODE"      DESTINATION="arch=x86_64"                    SCHEME="$SCHEME_MACOS"    RUN_TESTS="YES"

    - TOOL="XCODE"      DESTINATION="OS=11.4,name=iPhone X"          SCHEME="$SCHEME_IOS"      RUN_TESTS="YES"
    - TOOL="XCODE"      DESTINATION="OS=10.3.1,name=iPhone 7 Plus"   SCHEME="$SCHEME_IOS"      RUN_TESTS="YES"
    - TOOL="XCODE"      DESTINATION="OS=9.3,name=iPhone 6"           SCHEME="$SCHEME_IOS"      RUN_TESTS="YES"
  # - TOOL="XCODE"      DESTINATION="OS=8.4,name=iPhone 4S"          SCHEME="$SCHEME_IOS"      RUN_TESTS="YES"

    - TOOL="XCODE"      DESTINATION="OS=11.4,name=Apple TV 4K"       SCHEME="$SCHEME_TVOS"     RUN_TESTS="YES"
    - TOOL="XCODE"      DESTINATION="OS=10.2,name=Apple TV 1080p"    SCHEME="$SCHEME_TVOS"     RUN_TESTS="YES"
    - TOOL="XCODE"      DESTINATION="OS=9.2,name=Apple TV 1080p"     SCHEME="$SCHEME_TVOS"     RUN_TESTS="YES"

    - TOOL="XCODE"      DESTINATION="OS=4.3,name=Apple Watch - 42mm" SCHEME="$SCHEME_WATCHOS"  RUN_TESTS="NO"
    - TOOL="XCODE"      DESTINATION="OS=3.2,name=Apple Watch - 42mm" SCHEME="$SCHEME_WATCHOS"  RUN_TESTS="NO"
    - TOOL="XCODE"      DESTINATION="OS=2.2,name=Apple Watch - 42mm" SCHEME="$SCHEME_WATCHOS"  RUN_TESTS="NO"

    - TOOL="CARTHAGE"

before_install:
  - env
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - pod --version
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - set -o pipefail

  - echo "Validate podspec"
  - pod lib lint

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ENABLE_TESTABILITY=YES test | xcpretty;
    elif [ $TOOL == "XCODE" ]; then
      xcodebuild -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug build | xcpretty;
    fi

  # Build Framework in Release and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ENABLE_TESTABILITY=YES test | xcpretty;
    elif [ $TOOL == "XCODE" ]; then
      xcodebuild -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release build | xcpretty;
    fi

  # Fetch Stenographer and build with Carthage
  - if [ $TOOL == "CARTHAGE" ]; then
      echo 'github "stenographer/stenographer" "master"' > Cartfile;
      carthage update stenographer;
    fi
